"""Create Account Table

Revision ID: d3429ea1bad6
Revises:
Create Date: 2024-08-12 13:52:04.547754

"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3429ea1bad6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accounts', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('sub_tenant_id', sa.Integer(), nullable=False),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('status',
                  sa.Enum('ACTIVE', 'INACTIVE', name='status'),
                  nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('api_key'),
        sa.UniqueConstraint('name'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
