"""Create Gateway Configuration Table

Revision ID: b918c98d132e
Revises: 5cb23f1d2ac4
Create Date: 2024-08-12 14:12:28.983669

"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b918c98d132e'
down_revision: str | None = '5cb23f1d2ac4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Use the existing 'status' enum type, so do not create it again
    status_enum = ENUM('ACTIVE', 'INACTIVE', name='status', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gateway_configurations', sa.Column(
            'id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('gateway_id', sa.Integer(), nullable=False),
        sa.Column('configuration_details', sa.JSON(), nullable=False),
        sa.Column('status', status_enum, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['account_id'],
            ['accounts.id'],
        ), sa.ForeignKeyConstraint(
            ['gateway_id'],
            ['gateways.id'],
        ), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('name'),
        sa.UniqueConstraint('name',
                            'account_id',
                            'gateway_id',
                            name='uq_name_account_id_gateway_id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gateway_configurations')
    # ### end Alembic commands ###
